name: CI
on:
  workflow_dispatch:
  pull_request:
    type:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: pnpm install --immutable

      - name: Run ESLint
        run: pnpm lint
